
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dufhelmglvgvykyzeyns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1ZmhlbG1nbHZndnlreXpleW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODk1NTIsImV4cCI6MjA2NTc2NTU1Mn0.pvmz44tH8ILtbEdABmrXoh8H0CkBsX-REwbUs-3gEJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
